export const ADD_ING = 'ADD_INGREDIENT';
export const REMOVE_ING = 'REMOVE_INGREDIENT';
// export const ADD_INGREDIENTS = 'ADD';
// export const ADD_INGREDIENTS = 'ADD';

export const SET_ING = 'SET_INGREDIENTS';
export const FETCH_ING_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_SUCCESS= 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILED= 'PURCHASE_BURGER_FAILED';
