export const ADD_ING = 'ADD_INGREDIENT';
export const REMOVE_ING = 'REMOVE_INGREDIENT';
// export const ADD_INGREDIENTS = 'ADD';
// export const ADD_INGREDIENTS = 'ADD';
export const SET_ING = 'SET_INGREDIENTS';
export const FETCH_ING_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const INIT_ING='INIT_ING';
export const CLEAR_ING = 'CLEAR_ING';

export const PURCHASE_BURGER_SUCCESS= 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILED= 'PURCHASE_BURGER_FAILED';
export const PURCHASE_BRG_START = 'PURCHASE_BRG_START';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';
export const REMOVE_ORDER ='REMOVE_ORDER';


export const AUTH_START ='AUTH_START';
export const AUTH_SUCCESS ='AUTH_SUCCESS';
export const AUTH_FAIL ='AUTH_FAIL';
export const AUTH_LOGOUT ='AUTH_LOGOUT';
export const AUTH_INITIATE_LOGOUT ='AUTH_INITIATE_LOGOUT';
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH='AUTH';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
